### ISSUE TITLE
I have downloaded this code and it is working in visual studio IDE but not working in IIS

### ISSUE THREAD

**Issue by jubishkammily** [ashleydavis/nodejs-chart-rendering-example#1]
I have tested this code with ASP.net core Javascript services , but after hosting this to the Windows IIS , the nightmare call is not responding anything.

 I have tested another application using phantom js , its running fine in IIS environment . Seems like electron have some issue running in IIS. 

Any Idea on this ?

**Comment by ashleydavis** [comment]
So I can't help you there, I don't use IIS. Normally I run this on a Linux machine or on my development Windows PC. 

If you manage to get it working please update this issue and let me know how you did it.
